### ISSUE TITLE
ComfyUI SVD Pipline Error

### ISSUE THREAD

**Issue by arthursunbao** [siliconflow/onediff#820] opened 2024-04-16 02:40 UTC
#### A clear and concise description of what the bug is.
![企业微信截图_3c4e25dc-7d1d-4e0d-89d3-72435aec53ef](https://github.com/siliconflow/onediff/assets/8164429/239e2952-6e71-432e-9379-b60a57f8ac30)

  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1577, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/onediff/infer_compiler/oneflow/graph.py", line 19, in build
    return self.model(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/infer_compiler_registry/register_comfy/openaimodel.py", line 96, in forward
    h = forward_timestep_embed(
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 36, in forward_timestep_embed
    x = layer(x, emb, num_video_frames, image_only_indicator)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/infer_compiler_registry/register_comfy/openaimodel.py", line 223, in forward
    x = self.time_stack(x, emb.unflatten(0, shape=(batch_size, -1)))
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 230, in forward
    return checkpoint(
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/util.py", line 191, in checkpoint
    return func(*inputs)
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 261, in _forward
    emb_out = rearrange(emb_out, "b t c ... -> b c t ...")
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 487, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 410, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 231, in _apply_recipe
    backend = get_backend(tensor)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/_backends.py", line 52, in get_backend
    raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))
RuntimeError: Tensor type unknown to einops <class 'oneflow.Tensor'>

### Your environment
Linux

#### OneDiff git commit id
6b54c0872079dec578ca266b82fbb5f03f6b44b8

####  OneFlow version info
Run `python -m oneflow --doctor` and paste it here.

Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
path: ['/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20240415+cu118
git_commit: 67341c9
cmake_build_type: Release
rdma: True
mlir: True
enterprise: False

### How To Reproduce
Steps to reproduce the behavior(code or script):
run a svd comfyui workflow

**Comment by arthursunbao** [comment] 2024-04-16 04:13
full stack trace:
Traceback (most recent call last):
  File "/data/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/ComfyUI/nodes.py", line 1344, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/data/ComfyUI/nodes.py", line 1314, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/data/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "/data/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "/data/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 248, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "/data/ComfyUI/comfy/sample.py", line 37, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/ComfyUI/comfy/samplers.py", line 755, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/data/ComfyUI/comfy/samplers.py", line 657, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/ComfyUI/comfy/samplers.py", line 644, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/data/ComfyUI/comfy/samplers.py", line 623, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/data/ComfyUI/comfy/samplers.py", line 534, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/ComfyUI/comfy/k_diffusion/sampling.py", line 580, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/data/ComfyUI/comfy/samplers.py", line 272, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/data/ComfyUI/comfy/samplers.py", line 610, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/data/ComfyUI/comfy/samplers.py", line 613, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/data/ComfyUI/comfy/samplers.py", line 258, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/data/ComfyUI/comfy/samplers.py", line 216, in calc_cond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "/data/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/utils/deep_cache_speedup.py", line 119, in apply_model
    model_output, cache_h = model_patcher.deep_cache_unet(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/onediff/src/onediff/infer_compiler/utils/online_quantization_utils.py", line 48, in wrapper
    output = func(self, *args, **kwargs)
  File "/data/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 50, in wrapper
    output = func(self, *mapped_args, **mapped_kwargs)
  File "/data/onediff/src/onediff/infer_compiler/oneflow/utils.py", line 27, in wrapper
    return func(self, *args, **kwargs)
  File "/data/onediff/src/onediff/infer_compiler/utils/graph_management_utils.py", line 91, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data/onediff/src/onediff/infer_compiler/oneflow/deployable_module.py", line 99, in forward
    output = dpl_graph(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 295, in __call__
    self._compile(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 861, in _compile
    return self._dynamic_input_graph_cache._compile(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 121, in _compile
    return graph._compile(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 865, in _compile
    return self._compile_new(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 884, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1429, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1577, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/data/onediff/src/onediff/infer_compiler/oneflow/graph.py", line 19, in build
    return self.model(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/infer_compiler_registry/register_comfy/deep_cache_unet.py", line 71, in forward
    h = forward_timestep_embed(
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 36, in forward_timestep_embed
    x = layer(x, emb, num_video_frames, image_only_indicator)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/ComfyUI/custom_nodes/onediff_comfy_nodes/modules/oneflow/infer_compiler_registry/register_comfy/openaimodel.py", line 223, in forward
    x = self.time_stack(x, emb.unflatten(0, shape=(batch_size, -1)))
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 188, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 238, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 230, in forward
    return checkpoint(
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/util.py", line 191, in checkpoint
    return func(*inputs)
  File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 261, in _forward
    emb_out = rearrange(emb_out, "b t c ... -> b c t ...")
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 487, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 410, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 231, in _apply_recipe
    backend = get_backend(tensor)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/_backends.py", line 52, in get_backend
    raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))
RuntimeError: Tensor type unknown to einops <class 'oneflow.Tensor'>

**Comment by lixiang007666** [comment] 2024-04-18 15:52
What is your ComfyUI version (commit id)? @arthursunbao

**Comment by lixiang007666** [comment] 2024-04-22 02:42
![i2v](https://github.com/siliconflow/onediff/assets/54010254/b630d911-34c0-433c-a07a-bda2f1fd1543)

Based on the version information you provided, I tested the same workflow and could not reproduce the error. 🙂
You can try updating the versions of onediff and Comfy.

Additionally, in your error stack, I noticed calls to "deep_cache", but the current workflow does not use any Deep Cache nodes. This is a bit strange.
You can try deleting the cache of the previous graph and test again. The location of the graph cache is:

![image](https://github.com/siliconflow/onediff/assets/54010254/575cda94-bf2e-447b-91ad-db835fa3dca0)

@arthursunbao

**Comment by dk994023477** [comment] 2024-05-05 19:48
我遇到了同样的问题，卸载einops后重新安装就可以了

**Comment by strint** [comment] 2024-05-06 01:53
> 我遇到了同样的问题，卸载einops后重新安装就可以了

 What is the einops version number after you reinstall it？

**Comment by strint** [comment] 2024-05-06 01:54
> File "/data/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 261, in _forward
> emb_out = rearrange(emb_out, "b t c ... -> b c t ...")
> File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 487, in rearrange
> return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
> File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 410, in reduce
> return _apply_recipe(recipe, tensor, reduction_type=reduction)
> File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/einops.py", line 231, in _apply_recipe
> backend = get_backend(tensor)
> File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/einops/_backends.py", line 52, in get_backend
> raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))
> RuntimeError: Tensor type unknown to einops <class 'oneflow.Tensor'>

The error is in enops @lixiang007666 @dk994023477

**Comment by lixiang007666** [comment] 2024-05-06 02:05
I will close this issue. If the issue still cannot be resolved, you can reopen it.
@arthursunbao

**Closed** 2024-05-06 02:05 UTC
Labels: Request-bug, Response-need_minites, sig-comfyui
